name: GHA Composite WF Example 2 - V2

run-name:  "#${{ github.run_number }}. Build and Deploy on ${{ github.ref_type }} '${{ github.ref_name }}'. Triggered by: ${{ github.triggering_actor }}"

on:
  # Allow for manual execution and to trigger Secondary region deployments
  workflow_dispatch:
    inputs:
      ForceFailUat1:
        description: Fail UAT 1 deployment?
        type: boolean
        required: true
        default: false
      ForceFailUat2:
        description: Fail Uat 2 deployment?
        type: boolean
        required: true
        default: false 
        
  # Auto trigger when pushes to selected branch naming conventions occur
  #push: 
    #branches: [main, feat/**, feature/**, release/**]
    #paths-ignore: ['*.md']
  # Auto trigger when a release is created
  #release:
    #types: [published]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo "running docker build --target=build"
      - name: Test
        run: echo "running docker build --target=test"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Lint Tool
        run: echo "Setting up Lint tool"
      - name: Lint Code
        run: echo "Linting code"

  code-scan:
    runs-on: ubuntu-latest
    #if: ${{ inputs.BypassCodeScan != true }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Vericode
        run: echo "downloading Vericode"
      - name: Scan
        run: echo "scanning code"

  publish:
    runs-on: ubuntu-latest
    #if: ${{ always() && (inputs.BypassCodeScan == true || needs.code-scan.result == 'success') }}
    needs: [build-and-test, code-scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        run: echo "running docker build --target=final"
      - name: Download Trivy
        run: echo "downloading Trivy"
      - name: Aqua Image Scan
        run: echo "scanning image"
      - name: Login to ACR
        run: echo "logging into ACR"
      - name: Publish Image
        run: echo "publishing image with tag ???"
      - name: Logout of ACR
        run: echo "logging out of ACR"

  deploy-to-dev:
    runs-on: ubuntu-latest
    # Logic lets Job run if Code-Scan was skipped, but only triggers if we're not deploying to a Secondary region
    #if: ${{ always() && (inputs.DeployToUatSecondary == false && inputs.DeployToPrdSecondary == false) }}
    needs: [publish]
    environment: dev
    steps:
      - name: Deploy to Dev
        run: echo "deploying via helm"

  
  # Deploy to Test
  # --------------
  deploy-to-test-region-1:
    runs-on: ubuntu-latest
    #if: ${{ always() && (inputs.DeployToUatSecondary == false && inputs.DeployToPrdSecondary == false) }}
    needs: [publish]
    environment: test
    steps:
      - name: Deploy to Test
        run: echo "deploying via helm"

  deploy-to-test-region-2:
    runs-on: ubuntu-latest
    needs: [publish]
    environment: test
    steps:
      - name: Deploy to Test Region 1
        run: echo "deploying via helm"


  # Deploy to UAT
  # --------------
  deploy-to-uat-region-1:
    # only runnable if deploying a tag
    #if: ${{ always() && (startsWith(github.ref, 'refs/tags/') && inputs.DeployToUatSecondary == false && inputs.DeployToPrdSecondary == false) }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-test-region-1, deploy-to-test-region-2]
    environment: uat
    steps:
      - name: Check for Force Failure
        if: ${{ inputs.ForceFailUat1 == true }}
        run: |
          echo: "Deployment to UAT Region 1 was force failed by user"
          exit 1
      - name: Deploy to UAT Region 1
        run: echo "deploying via helm"

  deploy-to-uat-region-2:
    # only runnable if deploying a tag
    #if: ${{ always() && (startsWith(github.ref, 'refs/tags/') && inputs.DeployToUatSecondary == false && inputs.DeployToPrdSecondary == false) }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-test-region-1, deploy-to-test-region-2]
    environment: uat
    steps:
      - name: Check for Force Failure
        if: ${{ inputs.ForceFailUat2 == true }}
        run: |
          echo: "Deployment to UAT Region 2 was force failed by user"
          exit 1
      - name: Deploy to UAT Region 2
        run: echo "deploying via helm"


  # Deploy to PRD
  # --------------
  deploy-to-prd-region-1:
    # only runnable if deploying a tag
    #if: ${{ always() && (startsWith(github.ref, 'refs/tags/') && inputs.DeployToUatSecondary == false && inputs.DeployToPrdSecondary == false) }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-uat-region-1, deploy-to-uat-region-2]
    environment: prd
    steps:
      - name: Deploy to PRD Region 1
        run: echo "deploying via helm"
        
  deploy-to-prd-region-2:
    # only runnable if deploying a tag
    #if: ${{ always() && (startsWith(github.ref, 'refs/tags/') && inputs.DeployToPrdSecondary == true) }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-uat-region-1, deploy-to-uat-region-2]
    environment: prd
    steps:
      - name: Deploy to PRD Region 2
        run: echo "deploying via helm"
